include:
  - board: seeeduino_xiao_ble
    shield: fusen_left
#    snippet: studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    shield: fusen_right
#    snippet: studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    shield: settings_reset
